# Generated by Django 5.0 on 2024-05-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
    ]
