# Generated by Django 5.0 on 2024-05-27 00:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_genero_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='contact_form_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
